// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLUNS-G_sQILTNKlz1TTko9xi2DAum_rg',
    appId: '1:958764320171:web:90dbd7959dd4bdc491feee',
    messagingSenderId: '958764320171',
    projectId: 'twitch-fc515',
    authDomain: 'twitch-fc515.firebaseapp.com',
    storageBucket: 'twitch-fc515.firebasestorage.app',
    measurementId: 'G-VYDL3P740Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zlbL2DT8kcY6SZenkVsxWp3ORNzAzYY',
    appId: '1:958764320171:android:36ac9238eddfc02d91feee',
    messagingSenderId: '958764320171',
    projectId: 'twitch-fc515',
    storageBucket: 'twitch-fc515.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3E3Ki6r_o4rD6xYqdDxqaw9XvRJJ9j2E',
    appId: '1:958764320171:ios:73e536ba6b3422f491feee',
    messagingSenderId: '958764320171',
    projectId: 'twitch-fc515',
    storageBucket: 'twitch-fc515.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3E3Ki6r_o4rD6xYqdDxqaw9XvRJJ9j2E',
    appId: '1:958764320171:ios:73e536ba6b3422f491feee',
    messagingSenderId: '958764320171',
    projectId: 'twitch-fc515',
    storageBucket: 'twitch-fc515.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLUNS-G_sQILTNKlz1TTko9xi2DAum_rg',
    appId: '1:958764320171:web:461575e09a288d0d91feee',
    messagingSenderId: '958764320171',
    projectId: 'twitch-fc515',
    authDomain: 'twitch-fc515.firebaseapp.com',
    storageBucket: 'twitch-fc515.firebasestorage.app',
    measurementId: 'G-X94YEC8L5M',
  );
}
